### ISSUE TITLE
jersey-core-1.18 does not get pulled in by Maven

### ISSUE THREAD

**Issue by chadworth** [clearbit/clearbit-java#9]
@harlow looks like there's still one more issue to figure out in getting this pushed to Maven correctly

When trying to run the client from the version in Maven I get the error:

>Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jersey/spi/MessageBodyWorkers
	at com.clearbit.ApiClient.getClient(ApiClient.java:603)
Caused by: java.lang.ClassNotFoundException: com.sun.jersey.spi.MessageBodyWorkers
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

This is because jersey-core-1.18.jar isn't getting found, so I have to manually add that to my project. I'm not sure what's causing it to get excluded from Maven

**Comment by Snowda** [comment]
Should

< jersey-version>1.18< /jersey-version>

be

< jersey-version>1.18.3< /jersey-version>

in pom.xml or at least have a 1.18.x whatever version number is relevant?

**Comment by chadworth** [comment]
1.18 does exist. 1.18.x shouldn't be required. http://search.maven.org/#artifactdetails%7Ccom.sun.jersey%7Cjersey-core%7C1.18%7Cjar
